#!/bin/bash

#  This file is part of the VeriMAP tool.
#  See the file LICENSE.txt for license and copyright details.

function killtree() {
    local _pid=$1
    kill -STOP ${_pid}
    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
        killtree ${_child}
    done
    #echo "Killing ${_pid}, also know as '$(ps -p ${_pid} -o comm=)'"
    kill -9 ${_pid}
}

function clean_up {
  kill $PID
  exit 0
}

function timeout_clean_up {
  killtree $PID
  #echo "WARNING - command was terminated - timeout of $TO secs reached."
  #echo "unknown"
  exit 143
}

trap "clean_up" SIGINT
trap "timeout_clean_up" SIGTERM

# run the command in background
eval "$1 &"
PID=$!
TO=$2

if [[ -n $TO ]]; then
  # sleep for our timeout then kill the process if it is running
  eval "sleep $TO; kill -SIGTERM $$" 0<&- &>/dev/null &
  sleep_pid=$!
fi

# wait for state changes (it may wait forever if no TO has been provided)
wait $PID &>/dev/null

